# Generated by Django 4.2.4 on 2023-08-29 15:55

from django.db import migrations, models
import image_optimizer.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', image_optimizer.fields.OptimizedImageField(upload_to='blog-images/%Y/%m/%d')),
                ('title', models.CharField(max_length=256, verbose_name='Название блога')),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name='Название блога')),
                ('title_uz', models.CharField(max_length=256, null=True, verbose_name='Название блога')),
                ('text', models.TextField(verbose_name='Текст')),
                ('text_ru', models.TextField(null=True, verbose_name='Текст')),
                ('text_uz', models.TextField(null=True, verbose_name='Текст')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=256, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=256, verbose_name='Номер телефона')),
                ('date', models.DateField(verbose_name='Дата заказа')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя продукта')),
                ('name_ru', models.CharField(max_length=128, null=True, verbose_name='Имя продукта')),
                ('name_uz', models.CharField(max_length=128, null=True, verbose_name='Имя продукта')),
                ('description', models.TextField(verbose_name='Описание продукта')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание продукта')),
                ('description_uz', models.TextField(null=True, verbose_name='Описание продукта')),
                ('image', image_optimizer.fields.OptimizedImageField(upload_to='product-images/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя спонсора')),
                ('image', image_optimizer.fields.OptimizedImageField(upload_to='sponsor-images/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'спонсор',
                'verbose_name_plural': 'спонсоры',
            },
        ),
    ]
