# Generated by Django 4.2.4 on 2023-08-25 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='Имя спонсора'),
            preserve_default=False,
        ),
    ]
