# Generated by Django 4.2.4 on 2023-08-25 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_client_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата заказа'),
        ),
    ]
