# Generated by Django 4.2.4 on 2023-08-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_client_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Название блога'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Название блога'),
        ),
        migrations.AddField(
            model_name='client',
            name='fullname_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='client',
            name='fullname_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Описание продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Имя продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='Имя продукта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateField(verbose_name='Дата заказа'),
        ),
    ]
