# Generated by Django 4.2.4 on 2023-08-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_blog_text_ru_blog_text_uz_blog_title_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='fullname_ru',
        ),
        migrations.RemoveField(
            model_name='client',
            name='fullname_uz',
        ),
    ]
