# Generated by Django 4.2.4 on 2023-08-29 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_client_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата заказа'),
        ),
    ]
